### ISSUE TITLE
How can I run the MNIST+CoreML.playground code with my xcode?

### ISSUE THREAD

**Issue by bemoregt** [omaralbeik/mnist-coreml#1]
Hi, @omaralbeik 

How can I run the MNIST+CoreML.playground code with my xcode?

After loading your source, The run menu is not enabled..

How can ?

Thanks.

from @bemoregt.

**Comment by omaralbeik** [comment]
Hey @bemoregt, make sure assistant editor is open

<img width="1512" alt="screen shot 2018-11-05 at 19 46 58" src="https://user-images.githubusercontent.com/8127757/48012775-d5b83100-e133-11e8-8aee-fb00b7fb5f81.png">
