### ISSUE TITLE
[SOLVED] there was a problem running this playground

### ISSUE THREAD

**Issue by gobzer** [omaralbeik/mnist-coreml#2]
Hi,

If you encounter a "there was a problem running this playground" error on iPad, you may try to disable results to fix it.
![IMG_2298EB72C41F-1](https://user-images.githubusercontent.com/12876046/78246724-e6680480-74e9-11ea-9ccc-ddc86d86288c.jpeg)

Found it here
https://stackoverflow.com/questions/42695165/limited-number-of-views-in-swift-playgrounds

**Comment by omaralbeik** [comment]
Thanks @gobzer, I added a comment to readme with the instructions
